import { describe, expect, it } from "vitest";
import type { Track } from "../../../../packages/core-models/index";
import {
  assignClipIdsToTracks,
  inferClipDuration,
  normalizeTimelineClip,
} from "../lib/timelineClipAdapter";

describe("timeline clip adapter", () => {
  it("infers duration from MIDI note ends when no explicit duration exists", () => {
    expect(
      inferClipDuration({
        id: "clip-1",
        name: "Generated Bass",
        midiData: {
          notes: [
            { pitch: 36, velocity: 100, start: 0, duration: 0.5 },
            { pitch: 43, velocity: 96, start: 3.5, duration: 0.75 },
          ],
        },
      })
    ).toBe(4.25);
  });

  it("normalizes generated app clips into complete timeline clips", () => {
    const clip = normalizeTimelineClip(
      {
        id: "clip-1",
        name: "Drum Pattern",
        color: "#ef4444",
        qa: { pass: false, score: 72, warnings: ["Needs backbeat"] },
        reasoning: ["Generated by drum agent"],
        midiData: {
          notes: [{ pitch: 36, velocity: 127, start: 0, duration: 0.2 }],
        },
      },
      "track-1",
      2
    );

    expect(clip.trackId).toBe("track-1");
    expect(clip.type).toBe("midi");
    expect(clip.start).toBe(8);
    expect(clip.duration).toBe(1);
    expect(clip.loop).toBe(false);
    expect(clip.playback?.instrument).toBe("drum");
    expect(clip.metadata.generative).toBe(true);
    expect(clip.metadata.confidence).toBe(0.72);
    expect(clip.metadata.tags).toEqual(["qa-warning"]);
  });

  it("keeps existing track assignments and appends unassigned clips to fallback track", () => {
    const tracks: Track[] = [
      {
        id: "track-1",
        name: "Kick",
        type: "midi",
        color: "#ef4444",
        volume: 0.8,
        pan: 0,
        muted: false,
        solo: false,
        arm: false,
        clips: ["old-removed", "clip-1"],
        automationLanes: [],
      },
      {
        id: "track-2",
        name: "Bass",
        type: "midi",
        color: "#ff8c42",
        volume: 0.8,
        pan: 0,
        muted: false,
        solo: false,
        arm: false,
        clips: ["clip-2"],
        automationLanes: [],
      },
    ];

    expect(assignClipIdsToTracks(tracks, ["clip-1", "clip-2", "clip-3"], "track-1")).toEqual({
      "track-1": ["clip-1", "clip-3"],
      "track-2": ["clip-2"],
    });
  });
});
