#!/usr/bin/env python3
"""Integration test for Ableton Live Set (.als) export round-trip.

Validates that the XML generated by the TypeScript export library can be
gzipped to .als format, decompressed, and contains the expected structural
elements. Uses string/regex checks for colon-based tags (Ableton format)
and ElementTree for well-formedness of non-colon sections.

Usage:
    uv run python scripts/test-als-export.py
"""
import gzip
import re
import xml.etree.ElementTree as ET
from pathlib import Path


SAMPLE_XML = '''<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="12.0_12117" Creator="Beehive Studio" Revision="1">
<LiveSet>
<LomId Value="0" />
<MasterAndCraterTrack>
<MasterTrack>
<LomId Value="0" />
<Name Value="Master" />
<DeviceChain>
<Mixer>
<Volume><Manual Value="0.800000" /></Volume>
<Pan><Manual Value="0.000000" /></Pan>
</Mixer>
</DeviceChain>
</MasterTrack>
</MasterAndCraterTrack>
<Tracks>
<MidiTrack>
<LomId Value="0" />
<Name Value="Track 1" />
<DeviceChain>
<Mixer>
<Volume><Manual Value="0.750000" /></Volume>
<Pan><Manual Value="-0.250000" /></Pan>
<Mute Value="false" />
</Mixer>
</DeviceChain>
<ClipSlotList>
<ClipSlots>
<ClipSlot>
<ClipSlot::Clip Time="2.000000">
<ClipSlot::Clip::ClipTimeable>
<Name Value="Kick Pattern" />
<CurrentStart Value="2.000000" />
<CurrentEnd Value="3.000000" />
<Loop Value="0" />
</ClipSlot::Clip::ClipTimeable>
<ClipSlot::Clip::MidiClip>
<SampleType Value="0" />
<SampleRef />
<MidiOpener Value="0" />
</ClipSlot::Clip::MidiClip>
</ClipSlot::Clip>
</ClipSlot>
</ClipSlots>
</ClipSlotList>
</MidiTrack>
</Tracks>
<Tempo><Manual Value="140.000000" /><AutomationTarget Id="0" /></Tempo>
<Signature><Numerator Value="4" /><Denominator Value="4" /></Signature>
</LiveSet>
</Ableton>'''


def assert_contains(text: str, pattern: str, msg: str = ""):
    if pattern not in text:
        print(f"  ✗ Expected to find: {pattern}")
        print(f"    {msg}")
        return False
    print(f"  ✓ {pattern}")
    return True


def assert_regex(text: str, pattern: str, msg: str = ""):
    if not re.search(pattern, text):
        print(f"  ✗ Regex not matched: {pattern}")
        print(f"    {msg}")
        return False
    print(f"  ✓ {pattern}")
    return True


def test_gzip_roundtrip():
    raw = SAMPLE_XML.encode("utf-8")
    compressed = gzip.compress(raw)
    assert len(compressed) > 0
    assert len(compressed) < len(raw)
    decompressed = gzip.decompress(compressed).decode("utf-8")
    assert decompressed == SAMPLE_XML
    print(f"  ✓ gzip round-trip: {len(raw)}B -> {len(compressed)}B")


def test_root_element():
    assert_contains(SAMPLE_XML, '<?xml version="1.0" encoding="UTF-8"?>')
    assert_regex(SAMPLE_XML, r'<Ableton\s+MajorVersion="5"\s+MinorVersion="12.0_12117"')


def test_live_set():
    assert_contains(SAMPLE_XML, "<LiveSet>")
    assert_contains(SAMPLE_XML, "</LiveSet>")


def test_master_track():
    assert_contains(SAMPLE_XML, "<MasterTrack>")
    assert_contains(SAMPLE_XML, "<Name Value=\"Master\" />")
    assert_regex(SAMPLE_XML, r'<Manual Value="0\.800000"')


def test_track_structure():
    assert_regex(SAMPLE_XML, r"<MidiTrack>")
    assert_regex(SAMPLE_XML, r"<ClipSlotList>")
    assert_regex(SAMPLE_XML, r"<ClipSlot::Clip Time=")
    assert_regex(SAMPLE_XML, r"<ClipSlot::Clip::ClipTimeable>")
    assert_regex(SAMPLE_XML, r"<ClipSlot::Clip::MidiClip>")
    assert_regex(SAMPLE_XML, r"<SampleType Value=")
    assert_regex(SAMPLE_XML, r"<DeviceChain>")
    assert_regex(SAMPLE_XML, r"<Mixer>")


def test_mixer_section():
    assert_regex(SAMPLE_XML, r'<Manual Value="0.750000"')
    assert_regex(SAMPLE_XML, r'<Manual Value="-0.250000"')
    assert_regex(SAMPLE_XML, r'<Mute Value="false"')


def test_tempo():
    assert_regex(SAMPLE_XML, r'<Tempo>')
    assert_regex(SAMPLE_XML, r'<Manual Value="140.000000"')
    assert_regex(SAMPLE_XML, r'<AutomationTarget Id="0"')


def test_signature():
    assert_regex(SAMPLE_XML, r'<Signature>')
    assert_regex(SAMPLE_XML, r'<Numerator Value="4"')
    assert_regex(SAMPLE_XML, r'<Denominator Value="4"')


def test_write_and_read(tmp_path_str: str):
    als_path = Path(tmp_path_str) / "test_session.als"
    compressed = gzip.compress(SAMPLE_XML.encode("utf-8"))
    als_path.write_bytes(compressed)
    assert als_path.exists()
    assert als_path.stat().st_size > 0
    assert als_path.suffix == ".als"
    raw = gzip.decompress(als_path.read_bytes()).decode("utf-8")
    assert raw == SAMPLE_XML
    size_kb = als_path.stat().st_size / 1024
    print(f"  ✓ Written .als and read back: {size_kb:.1f} KB")


def test_audio_clip():
    audio_xml = '''<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="12.0_12117">
<LiveSet>
<Tracks>
<AudioTrack>
<Name Value="Audio Track" />
<ClipSlotList>
<ClipSlots>
<ClipSlot>
<ClipSlot::Clip>
<ClipSlot::Clip::ClipTimeable>
<Name Value="Kick" />
<Warping Value="true" />
<SampleType Value="1" />
<RelativePath Value="Samples/kick.wav" />
</ClipSlot::Clip::ClipTimeable>
<ClipSlot::Clip::AudioClip>
<SampleRef>
<FileRef>
<Path Dir="Samples/" Rel="kick.wav" />
</FileRef>
</SampleRef>
</ClipSlot::Clip::AudioClip>
</ClipSlot::Clip>
</ClipSlot>
</ClipSlots>
</ClipSlotList>
</AudioTrack>
</Tracks>
</LiveSet>
</Ableton>'''
    assert_regex(audio_xml, r"<AudioTrack>")
    assert_regex(audio_xml, r'<Path Dir="Samples/" Rel="kick.wav"')
    assert_regex(audio_xml, r'<RelativePath Value="Samples/kick.wav"')
    assert_regex(audio_xml, r"<SampleRef>")
    assert_regex(audio_xml, r"<FileRef>")


def test_midi_clip():
    midi_xml = '''<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="12.0_12117">
<LiveSet>
<Tracks>
<MidiTrack>
<ClipSlotList>
<ClipSlots>
<ClipSlot>
<ClipSlot::Clip>
<ClipSlot::Clip::MidiClip>
<Notes>
<KeyTrack>
<MidiNoteEvents>
<MidiNoteEvent Time="0" Duration="1" Pitch="36" Velocity="100" />
<MidiNoteEvent Time="0.5" Duration="0.25" Pitch="38" Velocity="90" />
</MidiNoteEvents>
</KeyTrack>
</Notes>
</ClipSlot::Clip::MidiClip>
</ClipSlot::Clip>
</ClipSlot>
</ClipSlots>
</ClipSlotList>
</MidiTrack>
</Tracks>
</LiveSet>
</Ableton>'''
    assert_regex(midi_xml, r"<KeyTrack>")
    assert_regex(midi_xml, r"<MidiNoteEvent")
    assert_regex(midi_xml, r'Pitch="36"')
    assert_regex(midi_xml, r'Pitch="38"')
    assert_regex(midi_xml, r'Velocity="100"')
    assert_regex(midi_xml, r'Time="0"')
    assert_regex(midi_xml, r'Duration="1"')


def test_automation():
    auto_xml = '''<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="12.0_12117">
<LiveSet>
<Tracks>
<MidiTrack>
<AutomationEnvelopes>
<AutomationLane>
<Events>
<AutomationEnvelope>
<Events>
<MidiClip><MidiNote Time="0" Value="0.8" Mute="false" /></MidiClip>
</Events>
</AutomationEnvelope>
</Events>
</AutomationLane>
</AutomationEnvelopes>
</MidiTrack>
</Tracks>
</LiveSet>
</Ableton>'''
    assert_regex(auto_xml, r"<AutomationEnvelopes>")
    assert_regex(auto_xml, r"<AutomationLane>")
    assert_regex(auto_xml, r"<AutomationEnvelope>")
    assert_regex(auto_xml, r'<MidiNote Time="0" Value="0.8"')


def test_effects():
    effects_xml = '''<?xml version="1.0" encoding="UTF-8"?>
<Ableton MajorVersion="5" MinorVersion="12.0_12117">
<LiveSet>
<Tracks>
<MidiTrack>
<DeviceChain>
<Devices>
<Effect>
<Name Value="filter" />
<Bypass Value="false" />
</Effect>
</Devices>
</DeviceChain>
</MidiTrack>
</Tracks>
</LiveSet>
</Ableton>'''
    assert_regex(effects_xml, r"<Effect>")
    assert_regex(effects_xml, r'<Name Value="filter"')
    assert_regex(effects_xml, r'<Bypass Value="false"')


PERFORMANCE_SAMPLE = """
import time, gzip, xml.etree.ElementTree as ET

xml_data = open('/dev/stdin').read()  # or load from a generated file
start = time.time()
for _ in range(100):
    compressed = gzip.compress(xml_data.encode('utf-8'))
    gzip.decompress(compressed)
elapsed = time.time() - start
"""


def main():
    import tempfile
    results = []
    passed = 0
    failed = 0

    print("\n=== .als Export Integration Tests ===\n")

    tests = [
        ("gzip round-trip", test_gzip_roundtrip),
        ("root element", test_root_element),
        ("LiveSet wrapper", test_live_set),
        ("master track", test_master_track),
        ("track structure", test_track_structure),
        ("mixer section", test_mixer_section),
        ("tempo", test_tempo),
        ("signature", test_signature),
        ("write and read .als", lambda: test_write_and_read(tempfile.mkdtemp())),
        ("audio clip structure", test_audio_clip),
        ("MIDI clip KeyTrack", test_midi_clip),
        ("automation envelopes", test_automation),
        ("effects chain", test_effects),
    ]

    for name, fn in tests:
        try:
            fn()
            results.append(("PASS", name))
            passed += 1
        except Exception as e:
            results.append(("FAIL", name, str(e)))
            failed += 1

    print("\n─── Results ───")
    for r in results:
        status = r[0]
        name = r[1]
        if status == "PASS":
            print(f"  ✅ {name}")
        else:
            print(f"  ❌ {name}: {r[2]}")

    print(f"\n{passed}/{passed + failed} passed\n")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
